# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

################################################
# Conditional Job
################################################
jobs:
- job: A
  steps:
  - script: echo hello

- job: B
  dependsOn: A
  condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
  steps:
  - script: echo this only runs for master


################################################
# Fan In Job
################################################
# jobs:
# - job: InitialA
#   steps:
#   - script: echo hello from initial A
# - job: InitialB
#   steps:
#   - script: echo hello from initial B
# - job: Subsequent
#   dependsOn:
#   - InitialA
#   - InitialB
#   steps:
#   - script: echo hello from subsequent

################################################
# stages:
# - stage: Build
#   jobs:
#   - job: Debug_Build
#     steps:
#     - script: echo Debug build complete
#   - job: Release_Build
#     dependsOn: Debug_Build
#     steps:
#     - script: echo Release build complete

################################################
# stages:
# - stage: A
#   jobs:
#   - job: A1
#     timeoutInMinutes: 10
#     pool:
#       vmImage: 'ubuntu-latest'
#     steps:
#     - bash: echo 'A1'
#   - job: A2
#     timeoutInMinutes: 10
#     pool:
#       vmImage: 'ubuntu-latest'
#     steps:
#     - bash: echo 'A2'
# - stage: B
#   jobs:
#   - job: B1
#     timeoutInMinutes: 10
#     pool:
#       vmImage: 'ubuntu-latest'
#     steps:
#     - bash: echo 'B1'
#   - job: B2
#     timeoutInMinutes: 10
#     pool:
#       vmImage: 'ubuntu-latest'
#     steps:
#     - bash: echo 'B2'

################################################
#jobs:
#- job: A
#  timeoutInMinutes: 10
#  pool:
#    vmImage: 'ubuntu-latest'
#  steps:
#  - bash: echo 'A'
# - job: B
#   timeoutInMinutes: 10
#   pool:
#     vmImage: 'ubuntu-latest'
#   steps:
#   - bash: echo 'B'

################################################
#trigger:
#- master

#pool:
#  vmImage: 'ubuntu-latest'

#steps:
#  - bash: echo "Hello World"

# To be enabled for later.
#steps:
#- task: Maven@3
#  inputs:
#    mavenPomFile: 'pom.xml'
#    mavenOptions: '-Xmx3072m'
#    javaHomeOption: 'JDKVersion'
#    jdkVersionOption: '1.8'
#    jdkArchitectureOption: 'x64'
#    publishJUnitResults: true
#    testResultsFiles: '**/surefire-reports/TEST-*.xml'
#    goals: 'package'

#- task: PublishCodeCoverageResults@1
#  inputs:
#    codeCoverageTool: "JaCoCo"
#    summaryFileLocation: "$(System.DefaultWorkingDirectory)/**/site/jacoco/jacoco.xml"
#    reportDirectory: "$(System.DefaultWorkingDirectory)/**/site/jacoco"
#    failIfCoverageEmpty: true
